title: 지완로그
tagline: 똑쟁이 도전기
description: "(참고이론) 제가알기론"

author:
  name:   G-WAN
  url:    https://jiwanst.github.io/
  avatar: ./logo.png

plugins:
  - jekyll-paginate

paginate: 5

categories_path: /categories/
tags_path: /tags/
